//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBibleApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibleTable
    {
        public int Id { get; set; }
        public string TestamentSelection { get; set; }
        public string BookSelection { get; set; }
        public int ChapterNumber { get; set; }
        public int VerseNumber { get; set; }
        public string VerseText { get; set; }
    }
}
